export const CHANGE_THEME_REQUEST = "@PORTOFOLIO/CHANGE_THEME_REQUEST";
export const CHANGE_THEME_FAILURE = "@PORTOFOLIO/CHANGE_THEME_FAILURE";
export const CHANGE_THEME_SUCCESS = "@PORTOFOLIO/CHANGE_THEME_SUCCESS";
