export const GET_PROJECTS_REQUEST = "@PORTOFOLIO/GET_PROJECTS_REQUEST";
export const GET_PROJECTS_FAILURE = "@PORTOFOLIO/GET_PROJECTS_FAILURE";
export const GET_PROJECTS_SUCCESS = "@PORTOFOLIO/GET_PROJECTS_SUCCESS";
