export const GET_SKILLS_REQUEST = "@PORTOFOLIO/GET_SKILLS_REQUEST";
export const GET_SKILLS_FAILURE = "@PORTOFOLIO/GET_SKILLS_FAILURE";
export const GET_SKILLS_SUCCESS = "@PORTOFOLIO/GET_SKILLS_SUCCESS";
